In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
data = pd.read_csv("../artifacts/sentiment_analysis.csv")


In [3]:
data.head()

id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

In [4]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
7915    False
7916    False
7917    False
7918    False
7919    False
Length: 7920, dtype: bool

In [6]:
data.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

In [7]:
### test preprossing

text preprocess

In [8]:
import re
import string


In [10]:

data["tweet"] = data["tweet"].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [11]:
data.head()

id  label                                              tweet
0   1      0  #fingerprint #pregnancy test https://goo.gl/h1...
1   2      0  finally a transparant silicon case ^^ thanks t...
2   3      0  we love this! would you go? #talk #makememorie...
3   4      0  i'm wired i know i'm george i was made that wa...
4   5      1  what amazing service! apple won't even talk to...

In [12]:
data["tweet"] = data["tweet"].apply(lambda x :" ".join(re.sub(r'^https?:\/\/.*[\r\n]*','',x,flags=re.MULTILINE) for x in x.split()))

In [13]:
data.head()


id  label                                              tweet
0   1      0  #fingerprint #pregnancy test  #android #apps #...
1   2      0  finally a transparant silicon case ^^ thanks t...
2   3      0  we love this! would you go? #talk #makememorie...
3   4      0  i'm wired i know i'm george i was made that wa...
4   5      1  what amazing service! apple won't even talk to...

In [15]:
def remove_punct(text):
    for punct in string.punctuation:
        text=text.replace(punct,'')
    return text
data["tweet"] = data["tweet"].apply(remove_punct)


In [16]:
data.head(5)

id  label                                              tweet
0   1      0  fingerprint pregnancy test  android apps beaut...
1   2      0  finally a transparant silicon case  thanks to ...
2   3      0  we love this would you go talk makememories un...
3   4      0  im wired i know im george i was made that way ...
4   5      1  what amazing service apple wont even talk to m...

In [17]:
string.punctuation


'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [20]:
data["tweet"] =data["tweet"].str.replace(r'\d+','',regex=True)

In [21]:
data.tail()


id  label                                              tweet
7915  7916      0  live out loud lol liveoutloud selfie smile son...
7916  7917      0  we would like to wish you an amazing day make ...
7917  7918      0  helping my lovely  year old neighbor with her ...
7918  7919      0  finally got my smart pocket wifi stay connecte...
7919  7920      0  apple barcelona apple store bcn barcelona trav...

In [22]:
!pip install nltk

     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     --------- ------------------------------ 10.2/42.0 kB ? eta -:--:--
     --------------------------- ---------- 30.7/42.0 kB 217.9 kB/s eta 0:00:01
     --------------------------- ---------- 30.7/42.0 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 42.0/42.0 kB 203.4 kB/s eta 0:00:00
     ---------------------------------------- 0.0/57.6 kB ? eta -:--:--
     ---------------------------------------- 57.6/57.6 kB 3.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   -- ------------------------------------- 0.1/1.5 MB 2.6 MB/s eta 0:00:01
   -- ------------------------------------- 0.1/1.5 MB 1.6 MB/s eta 0:00:01
   -- ------------------------------------- 0.1/1.5 MB 1.6 MB/s eta 0:00:01
   -- ------------------------------------- 0.1/1.5 MB 1.6 MB/s eta 0:00:01
   ---- ----------

In [23]:
import nltk

In [24]:
nltk.download('stopwords',download_dir='../static/model')

[nltk_data] Downloading package stopwords to ../static/model...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [26]:
with open('../static/model/corpora/stopwords/english','r') as file:
    sw=file.read().splitlines()
    

In [27]:
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [29]:
data["tweet"] = data["tweet"].apply(lambda x : " " .join(x for x in x.split() if x not in sw))

In [30]:
data['tweet'].tail()

7915    live loud lol liveoutloud selfie smile sony mu...
7916    would like wish amazing day make every minute ...
7917    helping lovely year old neighbor ipad morning ...
7918    finally got smart pocket wifi stay connected a...
7919    apple barcelona apple store bcn barcelona trav...
Name: tweet, dtype: object

stemming

In [31]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [32]:
data["tweet"] = data["tweet"].apply(lambda x : " " .join(ps.stem(x) for x in x.split()))

In [33]:
data['tweet'].head()


0    fingerprint pregnanc test android app beauti c...
1    final transpar silicon case thank uncl yay son...
2    love would go talk makememori unplug relax iph...
3    im wire know im georg made way iphon cute dave...
4    amaz servic appl wont even talk question unles...
Name: tweet, dtype: object

In [34]:
data['tweet'].tail()

7915    live loud lol liveoutloud selfi smile soni mus...
7916    would like wish amaz day make everi minut coun...
7917    help love year old neighbor ipad morn made rea...
7918    final got smart pocket wifi stay connect anyti...
7919    appl barcelona appl store bcn barcelona travel...
Name: tweet, dtype: object

In [35]:
data['tweet']


0       fingerprint pregnanc test android app beauti c...
1       final transpar silicon case thank uncl yay son...
2       love would go talk makememori unplug relax iph...
3       im wire know im georg made way iphon cute dave...
4       amaz servic appl wont even talk question unles...
                              ...                        
7915    live loud lol liveoutloud selfi smile soni mus...
7916    would like wish amaz day make everi minut coun...
7917    help love year old neighbor ipad morn made rea...
7918    final got smart pocket wifi stay connect anyti...
7919    appl barcelona appl store bcn barcelona travel...
Name: tweet, Length: 7920, dtype: object

create a vocabulary

In [39]:
from collections import Counter

In [47]:
vocab = Counter()

In [51]:
for sentence in data['tweet']:
    vocab.update(sentence.split())

In [52]:
vocab

Counter({'iphon': 4073,
         'appl': 2876,
         'samsung': 1395,
         'new': 1137,
         'phone': 1015,
         'follow': 885,
         'soni': 819,
         '…': 751,
         'ipad': 537,
         'rt': 525,
         'love': 499,
         'like': 455,
         'day': 426,
         'app': 416,
         'life': 415,
         'android': 414,
         'photo': 394,
         'get': 382,
         'io': 382,
         'galaxi': 361,
         'instagram': 358,
         'case': 348,
         'beauti': 322,
         'cute': 322,
         'gain': 311,
         'today': 309,
         'work': 306,
         'im': 294,
         'back': 294,
         'fuck': 293,
         'happi': 293,
         'photographi': 292,
         'game': 282,
         'got': 280,
         'fun': 277,
         'news': 265,
         'thank': 263,
         'music': 263,
         'time': 248,
         'make': 247,
         'updat': 236,
         'smile': 231,
         'instagood': 226,
         'funni': 223,
   

In [53]:
len(vocab)

15949

In [54]:
data.shape

(7920, 3)

In [56]:
tokens = [x for x in vocab if vocab[x] >10 ]

In [57]:
tokens


['test',
 'android',
 'app',
 'beauti',
 'cute',
 'health',
 'iger',
 'iphoneonli',
 'iphonesia',
 'iphon',
 'final',
 'case',
 'thank',
 'yay',
 'soni',
 'xperia',
 'love',
 'would',
 'go',
 'talk',
 'relax',
 'smartphon',
 'wifi',
 'connect',
 'im',
 'know',
 'made',
 'way',
 'home',
 'amaz',
 'servic',
 'appl',
 'wont',
 'even',
 'question',
 'pay',
 'stupid',
 'support',
 'softwar',
 'updat',
 'fuck',
 'phone',
 'big',
 'time',
 'happi',
 'us',
 'instap',
 'instadaili',
 'xperiaz',
 'new',
 'type',
 'c',
 'charger',
 'cabl',
 'uk',
 '…',
 'amazon',
 'year',
 'newyear',
 'start',
 'technolog',
 'samsunggalaxi',
 'iphonex',
 'shop',
 'listen',
 'music',
 'likeforlik',
 'photo',
 'fun',
 'selfi',
 'water',
 'camera',
 'picoftheday',
 'sun',
 'instagood',
 'boy',
 'outdoor',
 'hey',
 'make',
 'ipod',
 'dont',
 'color',
 'inch',
 'crash',
 'everi',
 'need',
 'realli',
 'drop',
 'ball',
 'design',
 'give',
 'anoth',
 'crazi',
 'purchas',
 'lol',
 'work',
 'hard',
 'play',
 'ipad',
 'batt

In [58]:
len(tokens)

1145

In [61]:
def save_vocabulary(lines,filename):
    data='\n'.join(lines)
    file = open(filename,'w',encoding='utf-8')
    file.write(data)
    file.close()

save_vocabulary(tokens,'../static/model/vocabulary.txt')
    

devied train and test data set

In [67]:
x = data['tweet']
y = data['label']  


In [70]:
!pip install scikit-learn

     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.6 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.6 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.6 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.6 kB 262.6 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.6 kB 196.9 kB/s eta 0:00:01
     -------------------------------------- 60.6/60.6 kB 248.0 kB/s eta 0:00:00
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.6 MB 2.3 MB/s eta 0:00:05
   ---------------------------------------- 0.1/10.6 MB 1.7 MB/s eta 0:00:07
   ---------------------------------------- 0.1/10.6 MB 1.7 MB/s eta 0:00:07
   ---------------------------------------- 0.1/10.6 MB 1.7 MB/s eta 0:00:07
    --------------------------------------- 0.2/10.6 MB 701.4 kB/s eta 0:00:15
    ---------

In [77]:
from sklearn.model_selection import train_test_split
x_train , x_test,y_train,y_test, = train_test_split(x,y,test_size=0.2)

In [81]:
x_test

2680    r kelli slate show cancel abus ‘rumours’ – mus...
6282    wireless charg water dust resist facial recogn...
3367    week yay one week birthday like beauti today g...
4713    omfg new iphon iphon white appl new bye htc ne...
2482        hannahholbrook appl run bunch crimin droidfan
                              ...                        
3773    appl may say main problem ear earpod appl alwa...
3740              ipad appl suck httpbitlybmfor appl ipad
5056    realiz im late fuckyou train hey fuck appl wha...
4652    retweet youd good laugh capn joe interview hil...
4508    ive never tso happi free period iphon keynot h...
Name: tweet, Length: 1584, dtype: object

In [82]:
x_train


2864    jake new ps soni ps playstat consol new yay ch...
7443           love new laptop nice fast comput soni vaio
4666    go start scrap book photo format mac harddriv ...
4111    im play big eye game applic funni appl android...
7406    would liter rather strand sea stuck appl store...
                              ...                        
1046    find iphon app saw day back forgot tht name go...
2353    fuck heart mother fucker bo activis ps soni pl...
518       holi crap look new iphon sexier look appl iphon
1929                        ive charger phone theyv broke
6151       vibrat dumb iphon mess wantanewphon iphonesuck
Name: tweet, Length: 6336, dtype: object

Vectoritation

In [89]:
def vectorizer(ds,vocabluary):
    vectorized_list =[]
    for sentence in ds:
        sentence_lst=np.zeros(len(vocabluary))

        for i in range(len(vocabluary)):
            if vocabluary[i] in sentence.split():
                sentence_lst[i] = 1

        vectorized_list.append(sentence_lst)
    vectorized_list_new = np.asarray(vectorized_list, dtype=np.float32)
    return vectorized_list_new
    

In [95]:
 vectorized_x_train = vectorizer(x_train,tokens)

In [96]:
 vectorized_x_test = vectorizer(x_test,tokens)

In [97]:
vectorized_x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [98]:
vectorized_x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [100]:
y_train.value_counts()


label
0    4704
1    1632
Name: count, dtype: int64

In [104]:
!pip install imbalanced-learn

   ---------------------------------------- 0.0/258.0 kB ? eta -:--:--
   - -------------------------------------- 10.2/258.0 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/258.0 kB 325.1 kB/s eta 0:00:01
   ---- ---------------------------------- 30.7/258.0 kB 325.1 kB/s eta 0:00:01
   ---- ---------------------------------- 30.7/258.0 kB 325.1 kB/s eta 0:00:01
   ------ -------------------------------- 41.0/258.0 kB 163.4 kB/s eta 0:00:02
   ------------ -------------------------- 81.9/258.0 kB 269.5 kB/s eta 0:00:01
   ------------- ------------------------- 92.2/258.0 kB 290.5 kB/s eta 0:00:01
   ------------------ ------------------- 122.9/258.0 kB 327.4 kB/s eta 0:00:01
   ------------------------ ------------- 163.8/258.0 kB 377.4 kB/s eta 0:00:01
   ------------------------- ------------ 174.1/258.0 kB 388.2 kB/s eta 0:00:01
   --------------------------------- ---- 225.3/258.0 kB 443.4 kB/s eta 0:00:01
   ------------------------------------ - 245.8/258.0 kB 

Handeling inblance dataset

In [106]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
vectorized_x_train_smote,y_train_smote = smote.fit_resample(vectorized_x_train,y_train)
print(vectorized_x_train_smote.shape,y_train_smote.shape)

(9408, 1145) (9408,)


In [108]:
y_train_smote.value_counts()

label
0    4704
1    4704
Name: count, dtype: int64

In [111]:
vectorized_x_train_smote

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.85325825, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], dtype=float32)

In [112]:
y_train_smote

0       0
1       0
2       1
3       0
4       1
       ..
9403    1
9404    1
9405    1
9406    1
9407    1
Name: label, Length: 9408, dtype: int64

In [113]:
vectorized_x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [114]:
y_test

2680    0
6282    0
3367    0
4713    0
2482    1
       ..
3773    1
3740    1
5056    1
4652    0
4508    0
Name: label, Length: 1584, dtype: int64

Model traing and evaluation

In [116]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [117]:
from sklearn.metrics import accuracy_score,f1_score, precision_score ,recall_score

def training_scores(y_act,y_pred):
    acc = round(accuracy_score(y_act,y_pred),3)
    f1 = round(f1_score(y_act,y_pred),3)
    pr = round(precision_score(y_act,y_pred),3)
    rec = round(recall_score(y_act,y_pred),3)
    print(f'Training scores:\n\tAccuracy = {acc}\n\tPrecision = {pr}\n\tRecall = {rec}\n\tF1_score = {f1}')

def validation_scores(y_act,y_pred):
    acc = round(accuracy_score(y_act,y_pred),3)
    f1 = round(f1_score(y_act,y_pred),3)
    pr = round(precision_score(y_act,y_pred),3)
    rec = round(recall_score(y_act,y_pred),3)
    print(f'Training scores:\n\tAccuracy = {acc}\n\tPrecision = {pr}\n\tRecall = {rec}\n\tF1_score = {f1}')


Logistic regression

In [128]:
lr = LogisticRegression()
lr.fit(vectorized_x_train_smote,y_train_smote)

y_train_pred = lr.predict(vectorized_x_train_smote)
training_scores(y_train_smote,y_train_pred)

y_test_pred = lr.predict(vectorized_x_test)
validation_scores(y_test,y_test_pred)

Training scores:
	Accuracy = 0.94
	Precision = 0.918
	Recall = 0.967
	F1_score = 0.942
Training scores:
	Accuracy = 0.868
	Precision = 0.688
	Recall = 0.86
	F1_score = 0.764


MultinomialNB

In [130]:
mnb = MultinomialNB()
mnb.fit(vectorized_x_train_smote,y_train_smote)

y_train_pred = mnb.predict(vectorized_x_train_smote)
training_scores(y_train_smote,y_train_pred)

y_test_pred = mnb.predict(vectorized_x_test)
validation_scores(y_test,y_test_pred)

Training scores:
	Accuracy = 0.908
	Precision = 0.872
	Recall = 0.957
	F1_score = 0.913
Training scores:
	Accuracy = 0.854
	Precision = 0.642
	Recall = 0.934
	F1_score = 0.761


DecisionTreeClassifier

In [131]:
dt =DecisionTreeClassifier()
dt.fit(vectorized_x_train_smote,y_train_smote)

y_train_pred = dt.predict(vectorized_x_train_smote)
training_scores(y_train_smote,y_train_pred)

y_test_pred = dt.predict(vectorized_x_test)
validation_scores(y_test,y_test_pred)

Training scores:
	Accuracy = 1.0
	Precision = 1.0
	Recall = 0.999
	F1_score = 1.0
Training scores:
	Accuracy = 0.841
	Precision = 0.678
	Recall = 0.688
	F1_score = 0.683


RandomForestClassifier


In [132]:
rfc = RandomForestClassifier()
rfc.fit(vectorized_x_train_smote,y_train_smote)

y_train_pred = rfc.predict(vectorized_x_train_smote)
training_scores(y_train_smote,y_train_pred)

y_test_pred = rfc.predict(vectorized_x_test)
validation_scores(y_test,y_test_pred)

Training scores:
	Accuracy = 1.0
	Precision = 1.0
	Recall = 1.0
	F1_score = 1.0
Training scores:
	Accuracy = 0.863
	Precision = 0.714
	Recall = 0.749
	F1_score = 0.731


SVC


In [133]:
svc = SVC()
svc.fit(vectorized_x_train_smote,y_train_smote)

y_train_pred = svc.predict(vectorized_x_train_smote)
training_scores(y_train_smote,y_train_pred)

y_test_pred = svc.predict(vectorized_x_test)
validation_scores(y_test,y_test_pred)

Training scores:
	Accuracy = 0.979
	Precision = 0.963
	Recall = 0.995
	F1_score = 0.979
Training scores:
	Accuracy = 0.884
	Precision = 0.729
	Recall = 0.853
	F1_score = 0.786


In [134]:
import pickle

with open('../static/model/model.pickle','wb') as file:
    pickle.dump(lr,file)